MeetSignIn/MeetSignIn/Areas/Admin/Controllers/PFSeasonAdminController.cs
using AutoMapper;
using MeetSignIn.ActionFilters;
using MeetSignIn.Areas.Admin.ViewModels.PFSeason;
using MeetSignIn.Models;
using MeetSignIn.Models.Others;
using MeetSignIn.Repositories;
using MeetSignIn.Repositories.T8Repositories;
using MeetSignIn.Utility.Helpers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MeetSignIn.Areas.Admin.Controllers
{
    [Authorize]
    [ErrorHandleAdminActionFilter]
    public class PFSeasonAdminController : BaseAdminController
    {
        private PFSeasonRepository pFSeasonRepository = new PFSeasonRepository(new MeetingSignInDBEntities());
        private comDepartmentRepository comDepartmentRepository = new comDepartmentRepository(new T8ERPEntities());

        public ActionResult Index(PFSeasonIndexView model)
        {
            var deptInfo = comDepartmentRepository.FindByDeptId(model.DeptId);
            model.DeptName = deptInfo == null ? "" : deptInfo.DeptName;
            var query = pFSeasonRepository.Query(model.IsOnline, model.ClassID, model.DeptId, model.Title);
            var pageResult = query.ToPageResult<PFSeason>(model);
            model.PageResult = Mapper.Map<PageResult<PFSeasonView>>(pageResult);

            return View(model);
        }

        public ActionResult Edit(int id = 0)
        {
            var model = new PFSeasonView();
            
            if (id != 0)
            {
                var query = pFSeasonRepository.FindBy(id);
                model = Mapper.Map<PFSeasonView>(query);
            }
            else
            {

            }

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Edit(PFSeasonView model)
        {
            if (ModelState.IsValid)
            {
                PFSeason data = Mapper.Map<PFSeason>(model);
                int adminId = AdminInfoHelper.GetAdminInfo().ID;

                if (model.ID == 0)
                {
                    model.ID = pFSeasonRepository.Insert(data);
                    ShowMessage(true, "新增成功");
                }
                else
                {
                    pFSeasonRepository.Update(data);
                    ShowMessage(true, "修改成功");
                }

                return RedirectToAction("Edit", new { id = model.ID, DeptId = model.DeptId });
            }

            return View(model);
        }

        public ActionResult Delete(int id)
        {   
            pFSeasonRepository.Delete(id);
            ShowMessage(true, "刪除成功");
            return RedirectToAction("Index");
        }
    
    }
}

MeetSignIn/MeetSignIn/Areas/Admin/Views/PFSeasonAdmin/Edit.cshtml
@model MeetSignIn.Areas.Admin.ViewModels.PFSeason.PFSeasonView
@{
    ViewBag.Title = "Edit";
    string title = Model.ID == 0 ? "新增評比季度" : "編輯評比季度";
}

<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        評比季度管理
    </h1>
</section>

<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">@title</h3>
                </div>

                @using (Html.BeginForm("Edit", "PFSeasonAdmin", FormMethod.Post, new { enctype = "multipart/form-data", @id = "EditForm" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.ID)
                    @Html.HiddenFor(model => model.DeptId)
                    @Html.HiddenFor(model => model.ClassID)

                    <div class="box-body">
                        <div class="nav-tabs-custom">
                            <div class="tab-content">
                                <div class="tab-pane active" id="tab_0">
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.Title)
                                        @Html.TextBoxFor(model => model.Title, new { @class = "form-control", @maxlength = "50" })
                                        @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                                    </div>

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.ThaiTitle)
                                        @Html.TextBoxFor(model => model.ThaiTitle, new { @class = "form-control", @maxlength = "100" })
                                    </div>

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.DeptId)                                       
                                        @Html.DropDownListFor(model => model.DeptId, Model.DeptOptions, "---選擇部門---", new { @class = "form-control" })
                                    </div>

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.StartDate)
                                        @Html.TextBoxFor(model => model.StartDate, new { @class = "form-control lock_switch" })
                                    </div>

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.EndDate)
                                        @Html.TextBoxFor(model => model.EndDate, new { @class = "form-control lock_switch" })
                                    </div>

                                    <div class="pretty p-switch p-fill" style="margin-bottom:10px;">
                                        @Html.CheckBoxFor(model => model.IsOnline, new { @class = "form-check-input" })
                                        <div class="state p-success">
                                            @Html.LabelFor(model => model.IsOnline)
                                        </div>
                                    </div>
                                </div>
                                <!-- /.tab-pane -->
                            </div>
                            <!-- /.tab-content -->
                        </div>
                        <!-- nav-tabs-custom -->
                    </div>

                    <div class="box-footer">
                        <button id="SaveBtn" type="submit" class="btn btn-primary">儲存</button>
                        @Html.ActionLink("取消/回列表", "Index", new { DeptId = Model.DeptId }, new { @class = "btn btn-default" })
                    </div>
                }
            </div>
        </div>
    </div>
</section>

@section scripts{
    <script>
        $(function () {
            //預設監聽
            setDateTime($("#StartDate"), 2);
            setDateTime($("#EndDate"), 2);          
        });

    </script>
}

MeetSignIn/MeetSignIn/Areas/Admin/Views/PFSeasonAdmin/Index.cshtml
@model MeetSignIn.Areas.Admin.ViewModels.PFSeason.PFSeasonIndexView
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        評比季度管理 - @Model.DeptId @Model.DeptName
    </h1>
</section>

<section class="content">
    <div class="row">
        <!--搜尋條件-->
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">搜尋</h3>
                    <a class="btn btn-default" href="@Url.Action("DeptPFEdit", "PFCategoryAdmin", new { DeptId = Model.DeptId + "_" + Model.DeptName })">返回評比分類管理</a>
                </div>
                @using (Html.BeginForm("Index", "PFSeasonAdmin", FormMethod.Get, new { @class = "form-horizontal" }))
                {
                    <div class="box-body">
                         <div class="form-group">
                            @Html.LabelFor(model => model.DeptId, new { @class = "col-sm-2 control-label" })
                            <div class="col-sm-4">
                                @Html.DropDownListFor(model => model.DeptId, Model.DeptOptions, "---選擇部門---", new { @class = "form-control" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Title, new { @class = "col-sm-2 control-label" })
                            <div class="col-sm-10">
                                @Html.TextBoxFor(model => model.Title, new { @class = "form-control", @placeholder = "季度標題" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.IsOnline, new { @class = "col-sm-2 control-label" })
                            <div class="col-sm-10">
                                @Html.EditorFor(model => model.IsOnline, "StatusDropDownList", new { @class = "form-control" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-info">搜尋</button>
                                @Html.ActionLink("新增季度", "Edit", "PFSeasonAdmin", new { DeptId = Model.DeptId }, new { @class = "btn btn-primary" })
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>

        <!--清單-->
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">評比季度列表</h3>
                </div>
                <div class="box-body">
                    <div id="dataList_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
                        @Html.Partial("_PageSizeAdmin", Model.PageResult)
                        <div class="row">
                            <div class="col-sm-12 table-responsive">
                                <table class="table table-bordered table-hover dataTable">
                                    <thead>
                                        <tr>
                                            <th>
                                                @Html.DisplayNameFor(x => x.Title)
                                            </th>
                                            <th>
                                                @Html.DisplayNameFor(x => x.DeptId)
                                            </th>
                                            <th>
                                                @Html.DisplayNameFor(x => x.StartDate)
                                            </th>
                                            <th>
                                                @Html.DisplayNameFor(x => x.EndDate)
                                            </th>
                                            <th>
                                                @Html.DisplayNameFor(x => x.IsOnline)
                                            </th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var item in Model.PageResult.Data)
                                        {
                                            <tr>
                                                <td>
                                                    @item.Title
                                                </td>
                                                <td>
                                                    <p>@Model.DeptOptions.Where(q => q.Value == item.DeptId).FirstOrDefault().Text</p>
                                                </td>
                                                <td>
                                                    @item.StartDate.ToString("yyyy-MM-dd HH:mm")
                                                </td>
                                                <td>
                                                    @item.EndDate.ToString("yyyy-MM-dd HH:mm")
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(model => item.IsOnline, "_Status")
                                                </td>
                                                <td>
                                                    @Html.ActionLink("編輯", "Edit", "PFSeasonAdmin", new { id = item.ID }, new { @class = "btn btn-primary" })
                                                </td>
                                            </tr>
                                        }
                                    </tbody>
                                    <tfoot>
                                        <tr>
                                            <th>
                                                @Html.DisplayNameFor(x => x.Title)
                                            </th>
                                            <th>
                                                @Html.DisplayNameFor(x => x.DeptId)
                                            </th>
                                            <th>
                                                @Html.DisplayNameFor(x => x.StartDate)
                                            </th>
                                            <th>
                                                @Html.DisplayNameFor(x => x.EndDate)
                                            </th>
                                            <th>
                                                @Html.DisplayNameFor(x => x.IsOnline)
                                            </th>
                                            <th></th>
                                        </tr>
                                    </tfoot>
                                </table>
                            </div>
                        </div>
                        @Html.Partial("_PageAdmin", Model.PageResult)
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

@section scripts{
    <script src="~/Scripts/Admin/page.js"></script>
}