MeetSignIn/MeetSignIn/Areas/Admin/Controllers/ThemeAdminController.cs
using AutoMapper;
using MeetSignIn.ActionFilters;
using MeetSignIn.Areas.Admin.ViewModels.Theme;
using MeetSignIn.Models;
using MeetSignIn.Models.Others;
using MeetSignIn.Repositories;
using MeetSignIn.Utility.Helpers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MeetSignIn.Areas.Admin.Controllers
{
    [Authorize]
    [ErrorHandleAdminActionFilter]
    public class ThemeAdminController : BaseAdminController
    {
        private ThemeRepository themeRepository = new ThemeRepository(new MeetingSignInDBEntities());

        public ActionResult Index(ThemeIndexView model)
        {
            var query = themeRepository.Query(model.IsOnline);
            var pageResult = query.ToPageResult<Theme>(model);
            model.PageResult = Mapper.Map<PageResult<ThemeView>>(pageResult);

            return View(model);
        }

        public ActionResult Edit(int id = 0)
        {
            var model = new ThemeView();
            if (id != 0)
            {
                var query = themeRepository.FindBy(id);
                model = Mapper.Map<ThemeView>(query);
            }
            else
            {

            }

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Edit(ThemeView model)
        {
            if (ModelState.IsValid)
            {
                Theme data = Mapper.Map<Theme>(model);
                int adminId = AdminInfoHelper.GetAdminInfo().ID;

                if (model.ID == 0)
                {
                    model.ID = themeRepository.Insert(data);
                    ShowMessage(true, "新增成功");
                }
                else
                {
                    themeRepository.Update(data);
                    ShowMessage(true, "修改成功");
                }

                return RedirectToAction("Edit", new { id = model.ID });
            }

            return View(model);
        }

        public ActionResult Delete(int id)
        {   
            themeRepository.Delete(id);
            ShowMessage(true, "刪除成功");
            return RedirectToAction("Index");
        }
    
    }
}

MeetSignIn/MeetSignIn/Areas/Admin/Views/ThemeAdmin/Edit.cshtml
@model MeetSignIn.Areas.Admin.ViewModels.Theme.ThemeView
@{
    ViewBag.Title = "Edit";
    string title = Model.ID == 0 ? "新增研訓類別" : "編輯研訓類別";
}

<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        研訓類別管理
    </h1>
</section>

<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">@title</h3>
                </div>

                @using (Html.BeginForm("Edit", "ThemeAdmin", FormMethod.Post, new { enctype = "multipart/form-data", @id = "EditForm" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.ID)

                    <div class="box-body">
                        <div class="nav-tabs-custom">
                            <div class="tab-content">
                                <div class="tab-pane active" id="tab_0">
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.Title)
                                        @Html.TextBoxFor(model => model.Title, new { @class = "form-control", @maxlength = "50" })
                                        @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                                    </div>
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.ResponsiblePerson)<br />
                                        @foreach (var item in Model.ResponsiblePersonOptions)
                                        {
                                            <div class="js-signer-Responsible btn btn-info" id="dept_@item.Value" style="margin: 2px 5px;">@item.Text</div>
                                        }
                                    </div>
                                    <div class="form-group">
                                        @Html.TextBoxFor(model => model.ResponsiblePerson, new Dictionary<string, object> { { "data-role", "tagsinput" }, { "class", "js-dept" } })
                                    </div>
                                    <div class="form-check pretty p-switch p-fill" style="margin-bottom:10px;">
                                        @Html.CheckBoxFor(model => model.IsOnline, new { @class = "form-check-input lock_switch" })
                                        <div class="state p-success">
                                            @Html.LabelFor(model => model.IsOnline, new { @class = "form-check-label", @style = "font-weight:bold; " })
                                        </div>
                                    </div>
                                </div>
                                <!-- /.tab-pane -->
                            </div>
                            <!-- /.tab-content -->
                        </div>
                        <!-- nav-tabs-custom -->
                    </div>

                    <div class="box-footer">
                        <button id="SaveBtn" type="submit" class="btn btn-primary">儲存</button>
                        @Html.ActionLink("取消/回列表", "Index", null, new { @class = "btn btn-default" })
                    </div>
                }
            </div>
        </div>
    </div>
</section>

@section scripts{
    <script>
        $(function () {
            var $selectedResponsibleType = $('#ResponsiblePerson');
            var remove;

            //ResponsiblePerson
            $selectedResponsibleType.on('itemAdded', function (event) {
                if (remove) {
                    $selectedResponsibleType.tagsinput('remove', remove);
                    remove = '';
                }
            });
            $('.js-signer-Responsible').on('click', function () {
                //var id = $(this).val();
                var val = $(this).text();
                $selectedResponsibleType.tagsinput('add', val);
            });
        });
    </script>
}

MeetSignIn/MeetSignIn/Areas/Admin/Views/ThemeAdmin/Index.cshtml
@model MeetSignIn.Areas.Admin.ViewModels.Theme.ThemeIndexView
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        研訓類別管理
    </h1>
</section>

<section class="content">
    <div class="row">
        <!--搜尋條件-->
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">搜尋</h3>
                </div>
                @using (Html.BeginForm("Index", "ThemeAdmin", FormMethod.Get, new { @class = "form-horizontal" }))
                {
                    <div class="box-body">
                        <div class="form-group">
                            @Html.LabelFor(model => model.IsOnline, new { @class = "col-sm-2 control-label" })
                            <div class="col-sm-10">
                                @Html.EditorFor(model => model.IsOnline, "StatusDropDownList", new { @class = "form-control" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-info">搜尋</button>
                                @Html.ActionLink("新增研訓類別", "Edit", "ThemeAdmin", new { }, new { @class = "btn btn-primary" })
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>

        <!--清單-->
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">研訓類別列表</h3>
                </div>
                <div class="box-body">
                    <div id="dataList_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
                        @Html.Partial("_PageSizeAdmin", Model.PageResult)
                        <div class="row">
                            <div class="col-sm-12 table-responsive">
                                <table class="table table-bordered table-hover dataTable">
                                    <thead>
                                        <tr>
                                            <th>
                                                @Html.DisplayNameFor(x => x.Title)
                                            </th>                                        
                                            <th>
                                                @Html.DisplayNameFor(x => x.IsOnline)
                                            </th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var item in Model.PageResult.Data)
                                        {
                                            <tr>
                                                <td>
                                                    @item.Title
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(model => item.IsOnline, "_Status")
                                                </td>
                                                <td>
                                                    @Html.ActionLink("編輯", "Edit", "ThemeAdmin", new { id = item.ID }, new { @class = "btn btn-primary" })
                                                </td>
                                            </tr>
                                        }
                                    </tbody>
                                    <tfoot>
                                        <tr>
                                            <th>
                                                @Html.DisplayNameFor(x => x.Title)
                                            </th>
                                            <th>
                                                @Html.DisplayNameFor(x => x.IsOnline)
                                            </th>
                                            <th></th>
                                        </tr>
                                    </tfoot>
                                </table>
                            </div>
                        </div>
                        @Html.Partial("_PageAdmin", Model.PageResult)
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

@section scripts{
    <script src="~/Scripts/Admin/page.js"></script>
}