MeetSignIn/MeetSignIn/Areas/Admin/Controllers/PersonKPIAdminController.cs
using AutoMapper;
using MeetSignIn.ActionFilters;
using MeetSignIn.Areas.Admin.ViewModels.FairlyPerson;
using MeetSignIn.Areas.Admin.ViewModels.KPI;
using MeetSignIn.Areas.Admin.ViewModels.Person;
using MeetSignIn.Areas.Admin.ViewModels.PersonKPI;
using MeetSignIn.Areas.Admin.ViewModels.PersonKPIMonth;
using MeetSignIn.Areas.Admin.ViewModels.PersonKPIState;
using MeetSignIn.Models;
using MeetSignIn.Models.Others;
using MeetSignIn.Models.T8.Join;
using MeetSignIn.Repositories;
using MeetSignIn.Repositories.T8Repositories;
using MeetSignIn.Utility.Helpers;
using Newtonsoft.Json;
//using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MeetSignIn.Areas.Admin.Controllers
{
    [Authorize]
    //[ErrorHandleAdminActionFilter]
    public class PersonKPIAdminController : BaseAdminController
    {
        // GET: Admin/PersonKPIAdmin
        private AdminRepository adminRepository = new AdminRepository(new MeetingSignInDBEntities());
        private AuditRepository auditRepository = new AuditRepository(new MeetingSignInDBEntities());
        private AuditLevelRepository auditLevelRepository = new AuditLevelRepository(new MeetingSignInDBEntities());
        private KPIRepository kPIRepository = new KPIRepository(new MeetingSignInDBEntities());
        private KPIRelationRepository kPIRelationRepository = new KPIRelationRepository(new MeetingSignInDBEntities());
        private PersonKPIRepository personKPIRepository = new PersonKPIRepository(new MeetingSignInDBEntities());
        private PersonKPIStateRepository personKPIStateRepository = new PersonKPIStateRepository(new MeetingSignInDBEntities());
        private PersonKPIMonthRepository personKPIMonthRepository = new PersonKPIMonthRepository(new MeetingSignInDBEntities());
        private CheckRepository checkRepository = new CheckRepository(new MeetingSignInDBEntities());
        private comPersonRepository comPersonRepository = new comPersonRepository(new T8ERPEntities());
        public ActionResult Index(FairlyPersonIndexView model)
        {
            var adminInfo = AdminInfoHelper.GetAdminInfo();
            //if (adminInfo.Type >= (int)AdminType.Employee || adminInfo.Type == (int)AdminType.Principal)
            if (adminInfo.Type >= (int)AdminType.Employee || adminInfo.IsPrincipal)
            {
                return RedirectToAction("QuarterEdit", new {PersonId = adminInfo.Account });
            }

            AuditLevelRepository auditLevelRepository = new AuditLevelRepository(new MeetingSignInDBEntities());
            if (adminInfo.Type < (int)AdminType.ClassSupervisor && adminInfo.Type != (int)AdminType.Sysadmin)
            {
                List<string> auditDepts = new List<string>();
                if (adminInfo.Type == (int)AdminType.Manager)
                {//主管審核
                    auditDepts = auditLevelRepository.Query(true, "", "", "", adminInfo.Account).Select(q => q.DeptId).ToList();
                }
                else if (adminInfo.Type == (int)AdminType.Vice)
                {//副總審核
                    auditDepts = auditLevelRepository.Query(true, "", "", adminInfo.Account, "").Select(q => q.DeptId).ToList();
                }
                else if (adminInfo.Type == (int)AdminType.President)
                {//總經理審核
                    auditDepts = auditLevelRepository.Query(true, "", adminInfo.Account, "", "").Select(q => q.DeptId).ToList();
                }
                model.DisplayDeptId = string.Join(",", auditDepts);
                if (auditDepts.Count() > 0 && string.IsNullOrEmpty(model.DeptId))
                {
                    model.DeptId = auditDepts.FirstOrDefault();
                }
            }

            var query = comPersonRepository.GetPersonQuery(model.PersonName, model.PersonId, model.DeptId);
            var pageResult = query.ToPageResult<GroupJoinPersonAndDepartment>(model);
            model.PageResult = Mapper.Map<PageResult<FairlyPersonView>>(pageResult);

            return View(model);
        }

        public ActionResult History(FairlyPersonView model)
        {
            if (string.IsNullOrEmpty(model.PersonId))
            {
                return RedirectToAction("Index");
            }

            var personInfo = comPersonRepository.FindByPersonID(model.PersonId);
            if (personInfo == null)
            {
                model.AuditStatus = "核准:人員離職";
                model.IsInvalid = false;
            }
            else
            {
                model.PersonName = personInfo.PersonName;
            }

            //var query = personKPIRepository.Query(null, null, model.KPIID, model.PersonId, "", 0, true) ;
            model.PersonKPIList = Mapper.Map<List<PersonKPIView>>(personKPIRepository.Query(null, null, model.KPIID, model.PersonId, "", 0, true).OrderByDescending(q => q.CreateDate));
            if (model.PersonKPIList != null && model.PersonKPIList.Count() > 0)
            {
                foreach (var item in model.PersonKPIList)
                {
                    item.FairlyKPITitle = "";
                    var deptKpiData = kPIRepository.GetById(item.KPIID);
                    if (deptKpiData == null)
                    {
                        continue;
                    }
                    var fairlyKpiData = kPIRepository.GetById(deptKpiData.ParentKPIID);
                    if (fairlyKpiData == null)
                    {
                        continue;
                    }
                    item.FairlyKPITitle = fairlyKpiData.Title;
                }
            }

            model.PersonKPIPercentageTasks = new List<PersonKPIPercentageTask>()
            {
                new PersonKPIPercentageTask() {PersonId = personInfo.PersonId, DeptId= personInfo.PersonId, Percentage = 0},
            };

            if (model.KPIID != 0)
            {
                var personKPI = personKPIRepository.GetById(model.KPIID);
                if (personKPI != null)
                {
                    model.KPITitle = personKPI.KPITitle;
                }
            }           

            return View(model);
        }

        public ActionResult QuarterEdit(string PersonId = "")
        {
            if (string.IsNullOrEmpty(PersonId))
            {
                return RedirectToAction("Index");
            }
            FairlyPersonView model = new FairlyPersonView();
            var personInfo = comPersonRepository.FindByPersonID(PersonId);
            if (personInfo == null)
            {
                model.AuditStatus = "核准:人員離職";
                model.IsInvalid = false;
            }

            model = Mapper.Map<FairlyPersonView>(personInfo);
            var relateKPIIdList = kPIRelationRepository.Query(0, personInfo.DeptId).Select(q => q.KPIID).ToList();
            var joinedKPIIdList = personKPIRepository.Query(null, true, 0, model.PersonId, "", 0, false).Select(q => q.KPIID).ToList();
            model.DeptKPIList = Mapper.Map<List<KPIView>>(kPIRepository.Query(true, "", 0, 2, 0, "", true).Where(q => relateKPIIdList.Contains(q.ID)));
            model.JoinableDeptKPIList = Mapper.Map<List<KPIView>>(model.DeptKPIList.Where(q => !joinedKPIIdList.Contains(q.ID)));
            foreach (var item in model.JoinableDeptKPIList)
            {
                if (item.ParentKPIID != 0)
                {
                    item.ParentKPITitle = kPIRepository.GetById(item.ParentKPIID).Title;
                }
                item.Dept = GetKPIDept(item.ID);
            }

            model.PersonKPIList = Mapper.Map<List<PersonKPIView>>(personKPIRepository.Query(null, true, 0, model.PersonId).OrderByDescending(q => q.CreateDate));
            if (model.PersonKPIList != null && model.PersonKPIList.Count() > 0)
            {
                foreach (var item in model.PersonKPIList)
                {
                    item.FairlyKPITitle = "";
                    var deptKpiData = kPIRepository.GetById(item.KPIID);
                    if (deptKpiData == null)
                    {
                        continue;
                    }                   
                    var fairlyKpiData = kPIRepository.GetById(deptKpiData.ParentKPIID);
                    if (fairlyKpiData == null)
                    {
                        continue;
                    }
                    item.FairlyKPITitle = fairlyKpiData.Title;
                }
            }

            model.PersonKPIPercentageTasks = new List<PersonKPIPercentageTask>()
            {
                new PersonKPIPercentageTask() {PersonId = personInfo.PersonId, DeptId= personInfo.PersonId, Percentage = 0},
            };

            //#region 審核資料
            //var auditInfo = auditRepository.Query(null, 0, (int)AuditType.PersonKPI, null, "", "", Convert.ToInt32(model.PersonId)).Where(q => q.Type == (int)AuditType.Seminar).OrderByDescending(q => q.ID).FirstOrDefault();
            //model.AuditState = auditInfo == null ? 0 : auditInfo.State;
            //model.AuditStatus = EnumHelper.GetDescription((AuditState)model.AuditState);
            //model.IsInvalid = auditInfo == null ? false : auditInfo.IsInvalid;
            //#endregion

            return View(model);
        }

        public ActionResult MonthsEdit(string PersonId ="")
        {
            if (string.IsNullOrEmpty(PersonId))
            {
                return RedirectToAction("Index");
            }
            FairlyPersonView model = new FairlyPersonView();
            var personInfo = comPersonRepository.FindByPersonID(PersonId);
            if (personInfo == null)
            {
                model.AuditStatus = "核准:人員離職";
                model.IsInvalid = false;
            }

            model = Mapper.Map<FairlyPersonView>(personInfo);

            var relateKPIIdList = kPIRelationRepository.Query(0, personInfo.DeptId).Select(q => q.KPIID).ToList();

MeetSignIn/MeetSignIn/Areas/Admin/Views/PersonKPIAdmin/Index.cshtml
@model MeetSignIn.Areas.Admin.ViewModels.FairlyPerson.FairlyPersonIndexView
@{
    ViewBag.Title = "Index";
    var adminInfo = MeetSignIn.Utility.Helpers.AdminInfoHelper.GetAdminInfo();
}

<section class="content-header">
    <h1>
        個人目標管理
    </h1>
    <ol class="breadcrumb">
        <li><a href="@Url.Action("Index", "HomeAdmin")"><i class="fa fa-home"></i> 首頁</a></li>
        <li class="active">個人目標管理</li>
    </ol>
</section>

<section class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">搜尋</h3>
                    </div>
                    <div class="box-body">
                        @using (Html.BeginForm("Index", "PersonKPIAdmin", FormMethod.Get, new { @class = "form-horizontal", @id = "List_Form" }))
                        {
                            @Html.HiddenFor(model => model.DeptId)
                            var selectedDeptList = string.IsNullOrEmpty(Model.DisplayDeptId) ? new List<string>() : Model.DisplayDeptId.Split(',').ToList();

                            <div class="form-group dept_selecter">
                                @Html.LabelFor(model => model.ParentDeptId, new { @class = "col-sm-2 control-label" })
                                <div class="col-sm-10">
                                    @foreach (var item in Model.DeptOptions.ToList())
                                    {
                                        if (selectedDeptList.Contains(item.Value) || adminInfo.Type < (int)MeetSignIn.Models.AdminType.Principal)
                                        {
                                            <input type="button" class="btn btn-sm dept_btn" style="margin:3px;" id="dept_@item.Value" value="@item.Text" />
                                        }
                                    }
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.PersonId, new { @class = "col-sm-2 control-label" })
                                <div class="col-sm-10">
                                    @Html.TextBoxFor(model => model.PersonId, new { @class = "form-control" })
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-info">搜尋</button>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
</section>

<section class="content">

        <div class="row">
            <div class="col-md-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">個人目標列表</h3>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <div id="dataList_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
                            @Html.Partial("_PageSizeAdmin", Model.PageResult)
                            <div class="row">
                                <div class="col-sm-12 table-responsive">
                                    <table class="table table-bordered table-hover dataTable">
                                        <thead>
                                            <tr>
                                                <th>@Html.DisplayNameFor(x => x.PersonName)</th>
                                                <th>@Html.DisplayNameFor(x => x.PersonId)</th>
                                                <th>@Html.DisplayNameFor(x => x.ParentDeptId)</th>
                                                <th width="20%"></th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @if (Model.PageResult.Data.Count() > 0)
                                            {
                                                foreach (var item in Model.PageResult.Data)
                                                {
                                                    <tr>
                                                        <td>@item.PersonName</td>
                                                        <td>@item.PersonId</td>
                                                        <td><label class="dept_tag">@Model.DeptOptions.Where(q => q.Value == item.DeptId.ToString()).FirstOrDefault().Text</label>
                                                        </td>
                                                        <td>
                                                            @*<a href="@Url.Action("Edit", "PersonKPIAdmin", new { PersonId = item.PersonId })" class="btn btn-primary" style="margin-bottom: 5px;">
                                                                <i class="fa fa-edit">原版編輯頁</i>
                                                            </a>*@
                                                            <a href="@Url.Action("QuarterEdit", "PersonKPIAdmin", new { PersonId = item.PersonId })" class="btn btn-primary" style="margin-bottom: 5px;">
                                                                <i class="fa fa-edit"> 編輯(季度)</i>
                                                            <a href="@Url.Action("MonthsEdit", "PersonKPIAdmin", new { PersonId = item.PersonId })" class="btn btn-primary" style="margin-bottom: 5px;">
                                                                <i class="fa fa-edit"> 編輯(月份</i>
                                                            </a>
                                                        </td>
                                                    </tr>
                                                }
                                            }
                                        </tbody>
                                        <tfoot>
                                            <tr>
                                                <th>@Html.DisplayNameFor(x => x.PersonName)</th>
                                                <th>@Html.DisplayNameFor(x => x.PersonId)</th>
                                                <th>@Html.DisplayNameFor(x => x.ParentDeptId)</th>
                                                <th></th>
                                            </tr>
                                        </tfoot>
                                    </table>
                                </div>
                            </div>
                            @Html.Partial("_PageAdmin", Model.PageResult)
                        </div>
                    </div>
                    <!-- /.box-body -->
                </div>
            </div>
        </div>
</section>

@section scripts{
    <script src="~/Scripts/Admin/page.js"></script>
    <script>
        $(function () {
            $('.dept_btn').on('click', function () {
                $('#DeptId').val($(this).attr('id').split('_')[1]);
                $('#List_Form').submit();
            });
            //$('#DeptId').on('change', function () {
            //    $('#List_Form').submit();
            //});
        })
    </script>
}