MeetSignIn/MeetSignIn/Areas/Admin/Controllers/QuizAdminController.cs
using AutoMapper;
using MeetSignIn.ActionFilters;
using MeetSignIn.Areas.Admin.ViewModels.OptionGroup;
using MeetSignIn.Areas.Admin.ViewModels.QNR;
using MeetSignIn.Areas.Admin.ViewModels.Quiz;
using MeetSignIn.Areas.Admin.ViewModels.QuizResult;
using MeetSignIn.Models;
using MeetSignIn.Models.Others;
using MeetSignIn.Repositories;
using MeetSignIn.Utility.Helpers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MeetSignIn.Areas.Admin.Controllers
{
    [Authorize]
    [ErrorHandleAdminActionFilter]
    public class QuizAdminController : BaseAdminController
    {
        private QNRRepository qNRRepository = new QNRRepository(new MeetingSignInDBEntities());
        private QNRQuestionRepository qNRQuestionRepository = new QNRQuestionRepository(new MeetingSignInDBEntities());
        private QNRResultRepository qNRResultRepository = new QNRResultRepository(new MeetingSignInDBEntities());
        private QuestionDBRepository questionDBRepository = new QuestionDBRepository(new MeetingSignInDBEntities());
        private OptionItemRepository optionItemRepository = new OptionItemRepository(new MeetingSignInDBEntities());

        // GET: Admin/ExamAdmin
        /// <summary>
        /// 試卷管理不需要連到列表
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        public ActionResult Index(QuizIndexView model)
        {
            var query = qNRRepository.Query(model.IsOnline, model.Title, model.Description, model.Year, model.Months);
            var pageResult = query.ToPageResult<QNR>(model);
            model.PageResult = Mapper.Map<PageResult<QuizView>>(pageResult);

            return View(model);
        }

        /// <summary>
        /// 編輯試卷
        /// </summary>
        /// <param name="tid"></param>
        /// <returns></returns>
        public ActionResult Edit(int tid = 0)
        {
            if (tid == 0)
            {
                return RedirectToAction("Index", "TrainingAdmin");
            }
            var adminInfo = AdminInfoHelper.GetAdminInfo();
            var model = new QNRView();
            model.TrainingID = tid;
            var qnrData = qNRRepository.FindByTrainingId(tid);
            if (qnrData != null)
            {
                model = Mapper.Map<QNRView>(qnrData);
                model.QuizQuestionList = Mapper.Map<List<ViewModels.QNR.QuizQuestionView>>(qNRQuestionRepository.Query(null, qnrData.ID));

                model.PersonResultList = new List<QNRPersonResultView>();
                var personIdList = qNRResultRepository.Query(qnrData.ID).Select(q => q.PersonId).Distinct().ToList();
                foreach (var personId in personIdList)
                {
                    var gradeData = new QNRPersonResultView();
                    gradeData.TotalPoints = 0;
                    var personQuizResult = qNRResultRepository.Query(qnrData.ID, 0, personId);
                    if (personQuizResult.Count() > 0)
                    {
                        var firstResult = personQuizResult.FirstOrDefault();
                        var personInfo = t8personRepository.FindByPersonId(personId);

                        gradeData.QNRID = qnrData.ID;
                        gradeData.PersonId = personId;
                        gradeData.PersonName = personInfo.Name;
                        gradeData.DeptId = personInfo.DeptId;
                        gradeData.DeptName = personInfo.DeptName;
                        gradeData.CreateDate = firstResult.CreateDate;

                        gradeData.TotalPoints = personQuizResult.Select(q => q.CorrectPoints).Sum();
                        gradeData.CorrectNum = personQuizResult.Where(q => q.CorrectPoints > 0).Count();
                        
                        model.PersonResultList.Add(gradeData);
                    }
                }
                model.FullPoints = model.QuizQuestionList.Select(q => q.Points).ToList().Sum();
            }
            else
            {
                qNRRepository.Insert(new QNR() {
                    TrainingID = tid,
                    Title = "",
                    Description = "",
                    Depts = "",
                    Year = DateTime.Now.Year,
                    Month = DateTime.Now.Month,
                    IsOnline = true,
                    CreateDate = DateTime.Now,
                    CreatePersonId = adminInfo.Account,
                });;
                model.QuizQuestionList = new List<ViewModels.QNR.QuizQuestionView>();
                model.PersonResultList = new List<QNRPersonResultView>();
            }            

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Edit(QNRView model)
        {
            if (ModelState.IsValid)
            {
                QNR data = Mapper.Map<QNR>(model);
                data.Depts = "";
                var adminInfo = AdminInfoHelper.GetAdminInfo();

                if (model.ID == 0)
                {
                    data.CreatePersonId = adminInfo.Account;
                    model.ID = qNRRepository.Insert(data);
                    ShowMessage(true, "新增成功");
                }
                else
                {
                    qNRRepository.Update(data);
                    ShowMessage(true, "修改成功");
                }
            }

            return RedirectToAction("Edit", new { tid = model.TrainingID });
        }

        public ActionResult CopyQuiz(int id)
        {
            try
            {
                var model = new QNRView();
                var query = qNRRepository.FindBy(id);
                model = Mapper.Map<QNRView>(query);

                #region 建立新試卷
                var data = Mapper.Map<QNR>(model);
                data.ID = 0;
                data.Title += "---複製";
                data.Description = query.Description;
                data.Depts = query.Depts;
                data.Year = query.Year;
                data.Month = query.Month;
                data.IsOnline = false;
                data.CreateDate = DateTime.Now;

                int nId = qNRRepository.Insert(data);
                #endregion

                var qnestionList = qNRQuestionRepository.Query(null, query.ID).ToList();

                #region 複製問題
                //新增名單                   
                foreach (var item in qnestionList)
                {
                    var result = qNRQuestionRepository.Insert(new QNRQuestion()
                    {
                        QNRID = nId,
                        Question = item.Question,
                        AnswerType = item.AnswerType,
                        OptionGroup = item.OptionGroup,
                        IsRequired = item.IsRequired,
                        Sort = item.Sort,
                    });
                }
                #endregion

                return RedirectToAction("Edit", new { id = nId });
            }
            catch (Exception ex)
            {

                throw;
            }
        }

        public ActionResult Delete(int id)
        {
            qNRRepository.Delete(id);
            ShowMessage(true, "刪除成功");
            return RedirectToAction("Index");
        }

        public string SaveQuestion(int id, int qnrId, string question, int sort, int points, string options)
        {
            try
            {
                if (id != 0)
                {
                    var query = qNRQuestionRepository.GetById(id);
                    //query.QNRID = qnrId;
                    query.Question = question;
                    //query.AnswerType = 4;
                    query.Sort = sort;
                    query.Options = options;
                    query.Points = points;
                    //query.OptionGroup = 0;
                    //query.IsRequired = true;
                    qNRQuestionRepository.Update(query);
                }
                else
                {
                    id = qNRQuestionRepository.Insert(new QNRQuestion()
                    {
                        QNRID = qnrId,
                        Question = question,
                        AnswerType = 4,
                        Sort = sort,
                        Options = options,
                        Points = points,
                        OptionGroup = 0,
                        IsRequired = true
                    });
                }

                //加入題庫
                var questionDBQuery = questionDBRepository.Query(null, question, 0);
                if (questionDBQuery.Count() <= 0)
                {
                    var questionData = qNRQuestionRepository.GetById(id);

                    var newqData = new QuestionDB();
                    newqData.Question = questionData.Question;
                    newqData.AnswerType = questionData.AnswerType;
                    newqData.OptionGroup = questionData.OptionGroup;
                    newqData.IsRequired = questionData.IsRequired;
                    newqData.Sort = questionData.Sort;
                    newqData.Points = questionData.Points;
                    newqData.Options = questionData.Options;
                    
                    newqData.UsedQNRIDs = id.ToString();
                    questionDBRepository.Insert(newqData);
                }
                else
                {
                    var questionDBData = questionDBRepository.Query().FirstOrDefault();
                    var qIdList = questionDBData.UsedQNRIDs.Split(',').ToList();
                    if (!qIdList.Contains(id.ToString()))
                    {
                        questionDBData.UsedQNRIDs += "," + id.ToString();
                        questionDBRepository.Update(questionDBData);
                    }                  
                }

                return "success";
            }

MeetSignIn/MeetSignIn/Areas/Admin/Views/QuizAdmin/Index.cshtml
@model MeetSignIn.Areas.Admin.ViewModels.QNR.QNRIndexView
@{
    var adminInfo = MeetSignIn.Utility.Helpers.AdminInfoHelper.GetAdminInfo();
    bool isSys = adminInfo.Type == (int)MeetSignIn.Models.AdminType.Sysadmin;
}
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        試卷管理
    </h1>
</section>

<section class="content">
    <div class="row">
        <!--搜尋條件-->
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">搜尋</h3>
                </div>
                @using (Html.BeginForm("Index", "QuizAdmin", FormMethod.Get, new { @class = "form-horizontal" }))
                {
                    <div class="box-body">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Title, new { @class = "col-sm-2 control-label" })
                            <div class="col-sm-10">
                                @Html.TextBoxFor(model => model.Title, new { @class = "form-control", @placeholder = "問卷標題" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Year, new { @class = "col-sm-2 control-label" })
                            <div class="col-sm-10">
                                @Html.DropDownListFor(model => model.Year, Model.YearOptions.OrderByDescending(q => q.Value), "---選擇年度---", new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Months, new { @class = "col-sm-2 control-label" })
                            <div class="col-sm-10">
                                @Html.DropDownListFor(model => model.Months, Model.MonthOptions, "---選擇月份---", new { @class = "form-control" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-info">搜尋</button>
                                @if (isSys)
                                {
                                    @Html.ActionLink("新增試卷", "Edit", "QNRAdmin", new { }, new { @class = "btn btn-primary" })
                                }
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>

        <!--清單-->
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">試卷列表</h3>
                </div>
                <div class="box-body">
                    <div id="dataList_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
                        @Html.Partial("_PageSizeAdmin", Model.PageResult)
                        <div class="row">
                            <div class="col-sm-12 table-responsive">
                                <table class="table table-bordered table-hover dataTable">
                                    <thead>
                                        <tr>
                                            <th>
                                                @Html.DisplayNameFor(x => x.Title)
                                            </th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var item in Model.PageResult.Data)
                                        {
                                            <tr>
                                                <td>
                                                    @item.Title
                                                </td>
                                                <td>
                                                    @Html.ActionLink("編輯", "Edit", "QNRAdmin", new { id = item.ID }, new { @class = "btn btn-primary" })
                                                </td>
                                            </tr>
                                        }
                                    </tbody>
                                    <tfoot>
                                        <tr>
                                            <th>
                                                @Html.DisplayNameFor(x => x.Title)
                                            </th>
                                            <th></th>
                                        </tr>
                                    </tfoot>
                                </table>
                            </div>
                        </div>
                        @Html.Partial("_PageAdmin", Model.PageResult)
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

@section scripts{
    <script src="~/Scripts/Admin/page.js"></script>
}